### ISSUE TITLE
Graphs fail to appear due to "Cannot render; PIL/Pillow is not installed"

### ISSUE THREAD

**Issue by edmorley** [mgedmin/dozer#1]
After following the instructions on:
https://github.com/mgedmin/dozer#tracking-down-memory-leaks
...and navigating to:
.../_dozer/index

The graphs for each object appear with the broken image icon. Viewing an image manually shows the error:
"Cannot render; PIL/Pillow is not installed"

It would be great if setup.py referenced either one of these packages, causing it to be automatically installed (albeit they rely on system packages, so likely still require manual steps), or if the README at least mentioned the need to install them :-)

**Comment by mgedmin** [comment]
I would be happy to merge a PR implementing either of these options.  (It is 2016 so we can forget about PIL and mention only Pillow.)

If you're unable or unwilling to produce a PR, please tell me, and I'll try to muster some energy in the next couple of weeks.

**Comment by edmorley** [comment]
Thank you for your reply. I may not have time to double back to this imminently, but will try at some point in the future :-)
