### ISSUE TITLE
"need profile_path"

### ISSUE THREAD

**Issue by Setheck** [mgedmin/dozer#16]
Followed README for profiler
```
from dozer import Profiler

# my_wsgi_app is a WSGI application
wsgi_app = Profiler(my_wsgi_app)
```
App just crashes with 
```    
assert profile_path, "need profile_path"
AssertionError: need profile_path
```

But there doesn't seem to be any info on what `profile_path` is supposed to be or how to set it?

**Comment by mgedmin** [comment]
Oops, that was embarrassing.  Added the missing docs.
